# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.11
#
# <auto-generated>
#
# Generated from file `smart_home.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module SmartHome
_M_SmartHome = Ice.openModule('SmartHome')
__name__ = 'SmartHome'

if 'OutOfRangeException' not in _M_SmartHome.__dict__:
    _M_SmartHome.OutOfRangeException = Ice.createTempClass()
    class OutOfRangeException(Ice.UserException):
        def __init__(self, reason=''):
            self.reason = reason

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::SmartHome::OutOfRangeException'

    _M_SmartHome._t_OutOfRangeException = IcePy.defineException('::SmartHome::OutOfRangeException', OutOfRangeException, (), False, None, (('reason', (), IcePy._t_string, False, 0),))
    OutOfRangeException._ice_type = _M_SmartHome._t_OutOfRangeException

    _M_SmartHome.OutOfRangeException = OutOfRangeException
    del OutOfRangeException

if 'HardwareErrorException' not in _M_SmartHome.__dict__:
    _M_SmartHome.HardwareErrorException = Ice.createTempClass()
    class HardwareErrorException(Ice.UserException):
        def __init__(self, details=''):
            self.details = details

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::SmartHome::HardwareErrorException'

    _M_SmartHome._t_HardwareErrorException = IcePy.defineException('::SmartHome::HardwareErrorException', HardwareErrorException, (), False, None, (('details', (), IcePy._t_string, False, 0),))
    HardwareErrorException._ice_type = _M_SmartHome._t_HardwareErrorException

    _M_SmartHome.HardwareErrorException = HardwareErrorException
    del HardwareErrorException

_M_SmartHome._t_Light = IcePy.defineValue('::SmartHome::Light', Ice.Value, -1, (), False, True, None, ())

if 'LightPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.LightPrx = Ice.createTempClass()
    class LightPrx(Ice.ObjectPrx):

        def TurnOn(self, context=None):
            return _M_SmartHome.Light._op_TurnOn.invoke(self, ((), context))

        def TurnOnAsync(self, context=None):
            return _M_SmartHome.Light._op_TurnOn.invokeAsync(self, ((), context))

        def begin_TurnOn(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Light._op_TurnOn.begin(self, ((), _response, _ex, _sent, context))

        def end_TurnOn(self, _r):
            return _M_SmartHome.Light._op_TurnOn.end(self, _r)

        def TurnOff(self, context=None):
            return _M_SmartHome.Light._op_TurnOff.invoke(self, ((), context))

        def TurnOffAsync(self, context=None):
            return _M_SmartHome.Light._op_TurnOff.invokeAsync(self, ((), context))

        def begin_TurnOff(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Light._op_TurnOff.begin(self, ((), _response, _ex, _sent, context))

        def end_TurnOff(self, _r):
            return _M_SmartHome.Light._op_TurnOff.end(self, _r)

        def IsOn(self, context=None):
            return _M_SmartHome.Light._op_IsOn.invoke(self, ((), context))

        def IsOnAsync(self, context=None):
            return _M_SmartHome.Light._op_IsOn.invokeAsync(self, ((), context))

        def begin_IsOn(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Light._op_IsOn.begin(self, ((), _response, _ex, _sent, context))

        def end_IsOn(self, _r):
            return _M_SmartHome.Light._op_IsOn.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.LightPrx.ice_checkedCast(proxy, '::SmartHome::Light', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.LightPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::Light'
    _M_SmartHome._t_LightPrx = IcePy.defineProxy('::SmartHome::Light', LightPrx)

    _M_SmartHome.LightPrx = LightPrx
    del LightPrx

    _M_SmartHome.Light = Ice.createTempClass()
    class Light(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::Light')

        def ice_id(self, current=None):
            return '::SmartHome::Light'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::Light'

        def TurnOn(self, current=None):
            raise NotImplementedError("servant method 'TurnOn' not implemented")

        def TurnOff(self, current=None):
            raise NotImplementedError("servant method 'TurnOff' not implemented")

        def IsOn(self, current=None):
            raise NotImplementedError("servant method 'IsOn' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_LightDisp)

        __repr__ = __str__

    _M_SmartHome._t_LightDisp = IcePy.defineClass('::SmartHome::Light', Light, (), None, ())
    Light._ice_type = _M_SmartHome._t_LightDisp

    Light._op_TurnOn = IcePy.Operation('TurnOn', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    Light._op_TurnOff = IcePy.Operation('TurnOff', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    Light._op_IsOn = IcePy.Operation('IsOn', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_bool, False, 0), ())

    _M_SmartHome.Light = Light
    del Light

if 'Color' not in _M_SmartHome.__dict__:
    _M_SmartHome.Color = Ice.createTempClass()
    class Color(object):
        def __init__(self, r=0, g=0, b=0):
            self.r = r
            self.g = g
            self.b = b

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.r)
            _h = 5 * _h + Ice.getHash(self.g)
            _h = 5 * _h + Ice.getHash(self.b)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_SmartHome.Color):
                return NotImplemented
            else:
                if self.r is None or other.r is None:
                    if self.r != other.r:
                        return (-1 if self.r is None else 1)
                else:
                    if self.r < other.r:
                        return -1
                    elif self.r > other.r:
                        return 1
                if self.g is None or other.g is None:
                    if self.g != other.g:
                        return (-1 if self.g is None else 1)
                else:
                    if self.g < other.g:
                        return -1
                    elif self.g > other.g:
                        return 1
                if self.b is None or other.b is None:
                    if self.b != other.b:
                        return (-1 if self.b is None else 1)
                else:
                    if self.b < other.b:
                        return -1
                    elif self.b > other.b:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_Color)

        __repr__ = __str__

    _M_SmartHome._t_Color = IcePy.defineStruct('::SmartHome::Color', Color, (), (
        ('r', (), IcePy._t_short),
        ('g', (), IcePy._t_short),
        ('b', (), IcePy._t_short)
    ))

    _M_SmartHome.Color = Color
    del Color

_M_SmartHome._t_RGBLight = IcePy.defineValue('::SmartHome::RGBLight', Ice.Value, -1, (), False, True, None, ())

if 'RGBLightPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.RGBLightPrx = Ice.createTempClass()
    class RGBLightPrx(_M_SmartHome.LightPrx):

        def SetColor(self, c, context=None):
            return _M_SmartHome.RGBLight._op_SetColor.invoke(self, ((c, ), context))

        def SetColorAsync(self, c, context=None):
            return _M_SmartHome.RGBLight._op_SetColor.invokeAsync(self, ((c, ), context))

        def begin_SetColor(self, c, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.RGBLight._op_SetColor.begin(self, ((c, ), _response, _ex, _sent, context))

        def end_SetColor(self, _r):
            return _M_SmartHome.RGBLight._op_SetColor.end(self, _r)

        def GetColor(self, context=None):
            return _M_SmartHome.RGBLight._op_GetColor.invoke(self, ((), context))

        def GetColorAsync(self, context=None):
            return _M_SmartHome.RGBLight._op_GetColor.invokeAsync(self, ((), context))

        def begin_GetColor(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.RGBLight._op_GetColor.begin(self, ((), _response, _ex, _sent, context))

        def end_GetColor(self, _r):
            return _M_SmartHome.RGBLight._op_GetColor.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.RGBLightPrx.ice_checkedCast(proxy, '::SmartHome::RGBLight', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.RGBLightPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::RGBLight'
    _M_SmartHome._t_RGBLightPrx = IcePy.defineProxy('::SmartHome::RGBLight', RGBLightPrx)

    _M_SmartHome.RGBLightPrx = RGBLightPrx
    del RGBLightPrx

    _M_SmartHome.RGBLight = Ice.createTempClass()
    class RGBLight(_M_SmartHome.Light):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::Light', '::SmartHome::RGBLight')

        def ice_id(self, current=None):
            return '::SmartHome::RGBLight'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::RGBLight'

        def SetColor(self, c, current=None):
            raise NotImplementedError("servant method 'SetColor' not implemented")

        def GetColor(self, current=None):
            raise NotImplementedError("servant method 'GetColor' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_RGBLightDisp)

        __repr__ = __str__

    _M_SmartHome._t_RGBLightDisp = IcePy.defineClass('::SmartHome::RGBLight', RGBLight, (), None, (_M_SmartHome._t_LightDisp,))
    RGBLight._ice_type = _M_SmartHome._t_RGBLightDisp

    RGBLight._op_SetColor = IcePy.Operation('SetColor', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_SmartHome._t_Color, False, 0),), (), None, (_M_SmartHome._t_OutOfRangeException,))
    RGBLight._op_GetColor = IcePy.Operation('GetColor', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), _M_SmartHome._t_Color, False, 0), ())

    _M_SmartHome.RGBLight = RGBLight
    del RGBLight

_M_SmartHome._t_DimmerLight = IcePy.defineValue('::SmartHome::DimmerLight', Ice.Value, -1, (), False, True, None, ())

if 'DimmerLightPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.DimmerLightPrx = Ice.createTempClass()
    class DimmerLightPrx(_M_SmartHome.LightPrx):

        def SetBrightness(self, level, context=None):
            return _M_SmartHome.DimmerLight._op_SetBrightness.invoke(self, ((level, ), context))

        def SetBrightnessAsync(self, level, context=None):
            return _M_SmartHome.DimmerLight._op_SetBrightness.invokeAsync(self, ((level, ), context))

        def begin_SetBrightness(self, level, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.DimmerLight._op_SetBrightness.begin(self, ((level, ), _response, _ex, _sent, context))

        def end_SetBrightness(self, _r):
            return _M_SmartHome.DimmerLight._op_SetBrightness.end(self, _r)

        def GetBrightness(self, context=None):
            return _M_SmartHome.DimmerLight._op_GetBrightness.invoke(self, ((), context))

        def GetBrightnessAsync(self, context=None):
            return _M_SmartHome.DimmerLight._op_GetBrightness.invokeAsync(self, ((), context))

        def begin_GetBrightness(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.DimmerLight._op_GetBrightness.begin(self, ((), _response, _ex, _sent, context))

        def end_GetBrightness(self, _r):
            return _M_SmartHome.DimmerLight._op_GetBrightness.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.DimmerLightPrx.ice_checkedCast(proxy, '::SmartHome::DimmerLight', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.DimmerLightPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::DimmerLight'
    _M_SmartHome._t_DimmerLightPrx = IcePy.defineProxy('::SmartHome::DimmerLight', DimmerLightPrx)

    _M_SmartHome.DimmerLightPrx = DimmerLightPrx
    del DimmerLightPrx

    _M_SmartHome.DimmerLight = Ice.createTempClass()
    class DimmerLight(_M_SmartHome.Light):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::DimmerLight', '::SmartHome::Light')

        def ice_id(self, current=None):
            return '::SmartHome::DimmerLight'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::DimmerLight'

        def SetBrightness(self, level, current=None):
            raise NotImplementedError("servant method 'SetBrightness' not implemented")

        def GetBrightness(self, current=None):
            raise NotImplementedError("servant method 'GetBrightness' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_DimmerLightDisp)

        __repr__ = __str__

    _M_SmartHome._t_DimmerLightDisp = IcePy.defineClass('::SmartHome::DimmerLight', DimmerLight, (), None, (_M_SmartHome._t_LightDisp,))
    DimmerLight._ice_type = _M_SmartHome._t_DimmerLightDisp

    DimmerLight._op_SetBrightness = IcePy.Operation('SetBrightness', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_short, False, 0),), (), None, (_M_SmartHome._t_OutOfRangeException,))
    DimmerLight._op_GetBrightness = IcePy.Operation('GetBrightness', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_short, False, 0), ())

    _M_SmartHome.DimmerLight = DimmerLight
    del DimmerLight

if 'ScheduleRule' not in _M_SmartHome.__dict__:
    _M_SmartHome.ScheduleRule = Ice.createTempClass()
    class ScheduleRule(object):
        def __init__(self, time='', targetTemp=0.0):
            self.time = time
            self.targetTemp = targetTemp

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_SmartHome.ScheduleRule):
                return NotImplemented
            else:
                if self.time != other.time:
                    return False
                if self.targetTemp != other.targetTemp:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_ScheduleRule)

        __repr__ = __str__

    _M_SmartHome._t_ScheduleRule = IcePy.defineStruct('::SmartHome::ScheduleRule', ScheduleRule, (), (
        ('time', (), IcePy._t_string),
        ('targetTemp', (), IcePy._t_float)
    ))

    _M_SmartHome.ScheduleRule = ScheduleRule
    del ScheduleRule

if '_t_DailyPlan' not in _M_SmartHome.__dict__:
    _M_SmartHome._t_DailyPlan = IcePy.defineSequence('::SmartHome::DailyPlan', (), _M_SmartHome._t_ScheduleRule)

_M_SmartHome._t_Thermostat = IcePy.defineValue('::SmartHome::Thermostat', Ice.Value, -1, (), False, True, None, ())

if 'ThermostatPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.ThermostatPrx = Ice.createTempClass()
    class ThermostatPrx(Ice.ObjectPrx):

        def SetTemperature(self, temp, context=None):
            return _M_SmartHome.Thermostat._op_SetTemperature.invoke(self, ((temp, ), context))

        def SetTemperatureAsync(self, temp, context=None):
            return _M_SmartHome.Thermostat._op_SetTemperature.invokeAsync(self, ((temp, ), context))

        def begin_SetTemperature(self, temp, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Thermostat._op_SetTemperature.begin(self, ((temp, ), _response, _ex, _sent, context))

        def end_SetTemperature(self, _r):
            return _M_SmartHome.Thermostat._op_SetTemperature.end(self, _r)

        def GetTemperature(self, context=None):
            return _M_SmartHome.Thermostat._op_GetTemperature.invoke(self, ((), context))

        def GetTemperatureAsync(self, context=None):
            return _M_SmartHome.Thermostat._op_GetTemperature.invokeAsync(self, ((), context))

        def begin_GetTemperature(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Thermostat._op_GetTemperature.begin(self, ((), _response, _ex, _sent, context))

        def end_GetTemperature(self, _r):
            return _M_SmartHome.Thermostat._op_GetTemperature.end(self, _r)

        def SetDailyPlan(self, plan, context=None):
            return _M_SmartHome.Thermostat._op_SetDailyPlan.invoke(self, ((plan, ), context))

        def SetDailyPlanAsync(self, plan, context=None):
            return _M_SmartHome.Thermostat._op_SetDailyPlan.invokeAsync(self, ((plan, ), context))

        def begin_SetDailyPlan(self, plan, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Thermostat._op_SetDailyPlan.begin(self, ((plan, ), _response, _ex, _sent, context))

        def end_SetDailyPlan(self, _r):
            return _M_SmartHome.Thermostat._op_SetDailyPlan.end(self, _r)

        def GetDailyPlan(self, context=None):
            return _M_SmartHome.Thermostat._op_GetDailyPlan.invoke(self, ((), context))

        def GetDailyPlanAsync(self, context=None):
            return _M_SmartHome.Thermostat._op_GetDailyPlan.invokeAsync(self, ((), context))

        def begin_GetDailyPlan(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Thermostat._op_GetDailyPlan.begin(self, ((), _response, _ex, _sent, context))

        def end_GetDailyPlan(self, _r):
            return _M_SmartHome.Thermostat._op_GetDailyPlan.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.ThermostatPrx.ice_checkedCast(proxy, '::SmartHome::Thermostat', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.ThermostatPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::Thermostat'
    _M_SmartHome._t_ThermostatPrx = IcePy.defineProxy('::SmartHome::Thermostat', ThermostatPrx)

    _M_SmartHome.ThermostatPrx = ThermostatPrx
    del ThermostatPrx

    _M_SmartHome.Thermostat = Ice.createTempClass()
    class Thermostat(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::Thermostat')

        def ice_id(self, current=None):
            return '::SmartHome::Thermostat'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::Thermostat'

        def SetTemperature(self, temp, current=None):
            raise NotImplementedError("servant method 'SetTemperature' not implemented")

        def GetTemperature(self, current=None):
            raise NotImplementedError("servant method 'GetTemperature' not implemented")

        def SetDailyPlan(self, plan, current=None):
            raise NotImplementedError("servant method 'SetDailyPlan' not implemented")

        def GetDailyPlan(self, current=None):
            raise NotImplementedError("servant method 'GetDailyPlan' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_ThermostatDisp)

        __repr__ = __str__

    _M_SmartHome._t_ThermostatDisp = IcePy.defineClass('::SmartHome::Thermostat', Thermostat, (), None, ())
    Thermostat._ice_type = _M_SmartHome._t_ThermostatDisp

    Thermostat._op_SetTemperature = IcePy.Operation('SetTemperature', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_float, False, 0),), (), None, (_M_SmartHome._t_OutOfRangeException,))
    Thermostat._op_GetTemperature = IcePy.Operation('GetTemperature', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_float, False, 0), ())
    Thermostat._op_SetDailyPlan = IcePy.Operation('SetDailyPlan', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_SmartHome._t_DailyPlan, False, 0),), (), None, ())
    Thermostat._op_GetDailyPlan = IcePy.Operation('GetDailyPlan', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), _M_SmartHome._t_DailyPlan, False, 0), ())

    _M_SmartHome.Thermostat = Thermostat
    del Thermostat

_M_SmartHome._t_RollerBlind = IcePy.defineValue('::SmartHome::RollerBlind', Ice.Value, -1, (), False, True, None, ())

if 'RollerBlindPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.RollerBlindPrx = Ice.createTempClass()
    class RollerBlindPrx(Ice.ObjectPrx):

        def SetPosition(self, percentage, context=None):
            return _M_SmartHome.RollerBlind._op_SetPosition.invoke(self, ((percentage, ), context))

        def SetPositionAsync(self, percentage, context=None):
            return _M_SmartHome.RollerBlind._op_SetPosition.invokeAsync(self, ((percentage, ), context))

        def begin_SetPosition(self, percentage, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.RollerBlind._op_SetPosition.begin(self, ((percentage, ), _response, _ex, _sent, context))

        def end_SetPosition(self, _r):
            return _M_SmartHome.RollerBlind._op_SetPosition.end(self, _r)

        def GetPosition(self, context=None):
            return _M_SmartHome.RollerBlind._op_GetPosition.invoke(self, ((), context))

        def GetPositionAsync(self, context=None):
            return _M_SmartHome.RollerBlind._op_GetPosition.invokeAsync(self, ((), context))

        def begin_GetPosition(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.RollerBlind._op_GetPosition.begin(self, ((), _response, _ex, _sent, context))

        def end_GetPosition(self, _r):
            return _M_SmartHome.RollerBlind._op_GetPosition.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.RollerBlindPrx.ice_checkedCast(proxy, '::SmartHome::RollerBlind', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.RollerBlindPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::RollerBlind'
    _M_SmartHome._t_RollerBlindPrx = IcePy.defineProxy('::SmartHome::RollerBlind', RollerBlindPrx)

    _M_SmartHome.RollerBlindPrx = RollerBlindPrx
    del RollerBlindPrx

    _M_SmartHome.RollerBlind = Ice.createTempClass()
    class RollerBlind(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::RollerBlind')

        def ice_id(self, current=None):
            return '::SmartHome::RollerBlind'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::RollerBlind'

        def SetPosition(self, percentage, current=None):
            raise NotImplementedError("servant method 'SetPosition' not implemented")

        def GetPosition(self, current=None):
            raise NotImplementedError("servant method 'GetPosition' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_RollerBlindDisp)

        __repr__ = __str__

    _M_SmartHome._t_RollerBlindDisp = IcePy.defineClass('::SmartHome::RollerBlind', RollerBlind, (), None, ())
    RollerBlind._ice_type = _M_SmartHome._t_RollerBlindDisp

    RollerBlind._op_SetPosition = IcePy.Operation('SetPosition', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_short, False, 0),), (), None, (_M_SmartHome._t_OutOfRangeException,))
    RollerBlind._op_GetPosition = IcePy.Operation('GetPosition', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_short, False, 0), ())

    _M_SmartHome.RollerBlind = RollerBlind
    del RollerBlind

_M_SmartHome._t_VenetianBlind = IcePy.defineValue('::SmartHome::VenetianBlind', Ice.Value, -1, (), False, True, None, ())

if 'VenetianBlindPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.VenetianBlindPrx = Ice.createTempClass()
    class VenetianBlindPrx(_M_SmartHome.RollerBlindPrx):

        def SetTilt(self, angle, context=None):
            return _M_SmartHome.VenetianBlind._op_SetTilt.invoke(self, ((angle, ), context))

        def SetTiltAsync(self, angle, context=None):
            return _M_SmartHome.VenetianBlind._op_SetTilt.invokeAsync(self, ((angle, ), context))

        def begin_SetTilt(self, angle, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.VenetianBlind._op_SetTilt.begin(self, ((angle, ), _response, _ex, _sent, context))

        def end_SetTilt(self, _r):
            return _M_SmartHome.VenetianBlind._op_SetTilt.end(self, _r)

        def GetTilt(self, context=None):
            return _M_SmartHome.VenetianBlind._op_GetTilt.invoke(self, ((), context))

        def GetTiltAsync(self, context=None):
            return _M_SmartHome.VenetianBlind._op_GetTilt.invokeAsync(self, ((), context))

        def begin_GetTilt(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.VenetianBlind._op_GetTilt.begin(self, ((), _response, _ex, _sent, context))

        def end_GetTilt(self, _r):
            return _M_SmartHome.VenetianBlind._op_GetTilt.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.VenetianBlindPrx.ice_checkedCast(proxy, '::SmartHome::VenetianBlind', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.VenetianBlindPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::VenetianBlind'
    _M_SmartHome._t_VenetianBlindPrx = IcePy.defineProxy('::SmartHome::VenetianBlind', VenetianBlindPrx)

    _M_SmartHome.VenetianBlindPrx = VenetianBlindPrx
    del VenetianBlindPrx

    _M_SmartHome.VenetianBlind = Ice.createTempClass()
    class VenetianBlind(_M_SmartHome.RollerBlind):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::RollerBlind', '::SmartHome::VenetianBlind')

        def ice_id(self, current=None):
            return '::SmartHome::VenetianBlind'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::VenetianBlind'

        def SetTilt(self, angle, current=None):
            raise NotImplementedError("servant method 'SetTilt' not implemented")

        def GetTilt(self, current=None):
            raise NotImplementedError("servant method 'GetTilt' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_VenetianBlindDisp)

        __repr__ = __str__

    _M_SmartHome._t_VenetianBlindDisp = IcePy.defineClass('::SmartHome::VenetianBlind', VenetianBlind, (), None, (_M_SmartHome._t_RollerBlindDisp,))
    VenetianBlind._ice_type = _M_SmartHome._t_VenetianBlindDisp

    VenetianBlind._op_SetTilt = IcePy.Operation('SetTilt', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_short, False, 0),), (), None, (_M_SmartHome._t_HardwareErrorException,))
    VenetianBlind._op_GetTilt = IcePy.Operation('GetTilt', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_short, False, 0), ())

    _M_SmartHome.VenetianBlind = VenetianBlind
    del VenetianBlind

# End of module SmartHome
